# Generated by Django 3.0.2 on 2020-01-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza1', '0002_auto_20200125_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('body', models.TextField(blank=True, db_index=True)),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
                ('data_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_pub'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data_pub']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-title']},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
