# Generated by Django 3.0.2 on 2020-01-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza1', '0004_productinbasket_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='nmb',
            field=models.IntegerField(default=1),
        ),
    ]
