# Generated by Django 3.0.2 on 2020-01-31 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza1', '0005_productinbasket_nmb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinbasket',
            options={},
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='body',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='data_pub',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='slug',
        ),
    ]
