# Generated by Django 3.0.2 on 2020-02-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza1', '0006_auto_20200131_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='title',
            new_name='products_name',
        ),
    ]
