# Generated by Django 3.0.2 on 2020-02-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza1', '0007_auto_20200201_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
