# Generated by Django 3.0.2 on 2020-02-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza1', '0008_productinbasket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
