# Generated by Django 3.0.2 on 2020-02-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza1', '0009_productinbasket_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
