# Generated by Django 3.0.2 on 2020-02-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza1', '0010_post_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='products_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
