# Generated by Django 3.0.2 on 2020-02-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza1', '0011_productinbasket_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='products_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
