# Generated by Django 3.0.2 on 2020-02-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza1', '0012_auto_20200205_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='mail',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
